#pragma once

#include <unistd.h>
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <cstdlib>
#include <cerrno>
#include <cctype>
#include <cmath>
#include <ctime>
#include <random>
#include <vector>
#include <list>
#include <map>
#include <unordered_map>
#include <stack>
#include <array>
#include <set>
#include <queue>
#include <deque>
#include <bitset>
#include <algorithm>
#include <iterator>
#include <utility>
#include <memory>
#include <numeric>
#include <limits>
#include <string>
#include <cstring>
#include <random>
#include <typeinfo>
#include <stdexcept>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/event.h>
#include <signal.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <dirent.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netdb.h>
