---
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - DB:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    volumes:
      - WordPress:/var/www/html
    ports:
      - "443:443"
    networks:
      - intra

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - WordPress:/var/www/html
    expose:
      - "9000"
    networks:
      - intra

volumes:
  DB:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/seunghan/data/var/lib/mysql
  WordPress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/seunghan/data/var/www/html

networks:
  intra:
    driver: bridge
