---
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - /home/seunghan/data/var/lib/mysql:/var/lib/mysql:rw
    expose:
      - "3306"
    networks:
      - intra

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - /home/seunghan/data/var/www/html:/var/www/html:rw
    ports:
      - "443:443"
    networks:
      - intra

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - /home/seunghan/data/var/www/html:/var/www/html:rw
    expose:
      - "9000"
    networks:
      - intra

networks:
  intra:
    driver: bridge
